scan_timeout = 45

format = """
$username[ in ](italic)\
$directory\
$cmd_duration\
$git_branch\
$git_status\
$rust\
$line_break\
$character\
"""
[username]
show_always = true
style_root = "#F7768E"
style_user = '#87D75F'
format = "[$user]($style)"
aliases = { "hunte" = "hunter" }

[directory]
truncation_length = 3
truncation_symbol = '…/'
disabled = false
style = "#5FAFFF"
read_only = ' '
read_only_style = '#F7768E'
use_os_path_sep = false

[cmd_duration]
min_time = 2_000
show_milliseconds = false
format = ' [ $duration]($style) '
style = '#414868'
disabled = false
show_notifications = false
min_time_to_notify = 45_000

[character]
success_symbol = "[\\$](#CCCCFF) "
error_symbol = "[\\$](#E0AF68) "

[c]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[hostname]
ssh_symbol = " "

[package]
symbol = "󰏗 "

[rust]
symbol = "󱘗 "

[sudo]
symbol = " "
style = "bold blue"
disabled = false
